[profile.default]
src = "src"
out = "out"
ast = true
ffi = true
build_info = true
extra_output = ["storageLayout"]

libs = ["lib"]
remappings = ["solady/=lib/solady/src"]

[fmt]
bracket_spacing = true

remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/, @openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"]



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
